### ISSUE TITLE
Observation Scheduler

### ISSUE THREAD

**Issue by amendochka** [yerkesobservatory/seo#9]
Given a list of observations (by RA-DEC), return a list of observations and what time to observe them.

**Comment by rprechelt** [comment]
I'll make sure that you get a Python list containing observations, and you make sure to return a list of tuples where each tuple is an (time, observation) pair telling me when to take that observation. 

See Viv for more details about the different algorithms. I think the most obvious one is to take images of the objects when they are each highest in the sky. 

Use this [file](https://github.com/yerkesobservatory/seo/blob/master/queue/queue/Schedule.py)

**Comment by rprechelt** [comment]
Updated link to new schedule ![file](https://github.com/yerkesobservatory/seo/blob/master/imqueue/schedule.py)

**Comment by amendochka** [comment]
Currently algorithm is when object is highest in the sky. Could try to make a new one for taking images in order of position?
